### ISSUE TITLE
How to download this docker projet ?

### ISSUE THREAD

**Issue by titou4307** [daniel0076/docker-jdownloader-2#1]
I have a message like this :

No such image:
daniel0076/jdownoader-2:latest

Any solution ?

thanks

**Comment by daniel0076** [comment]
Hi @titou4307 ,

Since I didn't tag my image with "latest", your command will fail.

You may use the command:

`docker pull daniel0076/jdownloader-2:aarch64-v0.1`

Or perhaps in your UI

`daniel0076/jdownloader-2:aarch64-v0.1`

Here is the reference from docker hub: https://hub.docker.com/r/daniel0076/jdownloader-2/tags

I will tag my image with latest later if I got some chances lol.

Thanks. Regards.

**Comment by titou4307** [comment]
Many thanks for your response

I below your indication
